baseproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('', TemplateView.as_view(template_name="login/index.html")),
    path('logouts/', views.logout_view, name="logout_view"),
    path('admin/', admin.site.urls),
    # path('logout/', LogoutView),
    path('accounts/', include('allauth.urls')),
    path('fitapp/', include('fitapp.urls'))
]

fitapp/urls.py
from django.urls import path
from . import views


app_name = 'fitapp'
urlpatterns = [
    path('progress/', views.ProgressBar, name='progress'),
    path('Logs/', views.LogReq, name='Logs'),
    path('viewLogs/', views.viewLogs, name='viewLogs'),
    path('achievements/', views.Achievements, name='achievements'),
    path('achievements/update/<int:user_id>', views.update, name='update'),
    path('viewLogs/<int:logs_id>', views.log, name='log'),
    path('viewLogs/<int:logs_id>/comment', views.post_detail, name='post_detail'),
    path('Logs/updatelogs/<int:user_id>', views.updatelogs, name='updatelogs'),
    path('viewLogs/<int:logs_id>/deleteLog', views.deleteLog, name='deleteLog'),
    path('viewLogs/<int:logs_id>/shareable', views.shareable, name='shareable'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('userLogs/<int:user_id>', views.userLogs, name='userLogs')
]

fitapp/models.py
"""
*  REFERENCES
*
*  Title: Creating Comments System With Django
*  Author: Django Central
*  URL: https://djangocentral.com/creating-comments-system-with-django/
"""
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.IntegerField(default=0)
    current = models.IntegerField(default=0) # bar part of progress bar
    maximum = models.IntegerField(default=100) # maximum length bar can be
    def __str__(self):
        return f'{self.user.username} Profile'

EXERCISE_CHOICES = (
    ('pushup','pushup'),
    ('situp', 'situp'),
    ('pullup','pullup'),
    ('squat','squat'),
    ('burpee','burpee'),
    ('lift','lift'),
    ('run','run'),
    ('stretches','stretches'),
    ('other','other'),
)

INTENSITY_CHOICES = (
    ('light','light'),
    ('moderate', 'moderate'),
    ('vigorous','vigorous'),
)

DEFAULT_duration = 1
MAX_duration = 500
MIN_duration = 0

#DURATION should be slider
#DATE should be found using datepicker

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

# logs model
class Logs(models.Model):
    exercise = models.CharField(max_length=10, choices=EXERCISE_CHOICES, default='other')#, help_text="title.")
    date = models.DateField()
    duration = models.PositiveSmallIntegerField( name=('duration'), default=DEFAULT_duration,validators=[MinValueValidator(MIN_duration), MaxValueValidator(MAX_duration)])
    intensity = models.CharField(max_length=10, choices=INTENSITY_CHOICES, default='light')
    area = models.CharField(max_length=10)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.date + ":" + self.exercise + "\n"

# begin Creating Comments code #
class Comment(models.Model):
    post = models.ForeignKey(Logs,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    #email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)
# end Creating Comments code #

fitapp/forms.py
from django import forms
from .models import Logs, Comment

from django.core.exceptions import ValidationError
from datetime import date

class DateInput(forms.DateInput):
    input_type = 'date'

class RangeInput(forms.NumberInput):
    input_type = 'range'

class LogsForm(forms.ModelForm):
    def clean_date(self):
            print(date.today())
            thisday = self.cleaned_data['date']
            if thisday > date.today():
                raise forms.ValidationError("The entered date is in the future.")                
            return thisday

    class Meta:
        model = Logs
        fields = ('exercise', 'date', 'intensity', 'area', 'duration')
        widgets = {
            'date': DateInput(),
            'duration': forms.NumberInput(attrs={'max': '500', 'type':'range', 'step': '1', 'min': '0', 'id':'myRange'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

fitapp/views.py
"""
*  REFERENCES
*
*  Title: Creating Comments System With Django
*  Author: Django Central
*  URL: https://djangocentral.com/creating-comments-system-with-django/
"""
from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from .models import Logs, Profile, User, Comment
from .forms import LogsForm, CommentForm
from django.contrib.auth.backends import BaseBackend
from django.db.models import F

from django.contrib.auth.decorators import login_required

@login_required(login_url='/')
def ProgressBar(request):
    return render(request, 'fitapp/progress.html')
    # def get(self, request):
    #     object1 = User.objects.all()
    #     return 


@login_required(login_url='/')
def LogReq(request): ##doesn't need index. does have list though. Can be a generic detailview.
    try:
        user = request.user
        form = LogsForm()
    except User.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'fitapp/Logs.html', {'user': user, 'form': form})

@login_required(login_url='/')
def updatelogs(request, user_id):
    user = User.objects.get(pk=user_id)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LogsForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            #form.save()
            log = Logs(exercise=form.cleaned_data['exercise'],
                date=form.cleaned_data['date'], 
                duration=form.cleaned_data['duration'],
                intensity=form.cleaned_data['intensity'],
                area=form.cleaned_data['area'],
                owner=request.user.profile
            )
            log.save()
            user = User.objects.get(pk=user_id)
            user.profile.current = user.profile.current + log.duration
            if log.intensity == 'light':
                user.profile.current = user.profile.current + 5
            elif log.intensity == 'moderate':
                user.profile.current = user.profile.current + 10
            elif log.intensity == 'vigorous':
                user.profile.current = user.profile.current + 15
            while user.profile.current >= 100:
                print(user.profile.current)
                user.profile.current = user.profile.current - 100
                user.profile.level = user.profile.level + 1
            user.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('fitapp:viewLogs'))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = LogsForm()
    return render(request, 'fitapp/Logs.html', {'form': form, 'user': user})

@login_required(login_url='/')
def viewLogs(request):
    template = loader.get_template('fitapp/viewLogs.html')
    if request.method != 'GET':
        raise Exception('Should be a GET request')
    logs = Logs.objects.order_by("-date") 
    my_logs = Logs.objects.filter(owner=request.user.profile).all()
    context = {'logs' : logs, 'my_logs' : my_logs}
    return HttpResponse(template.render(context, request))

def userLogs(request, user_id):
    print(user_id)
    user = User.objects.get(pk=user_id)
    user_logs = Logs.objects.filter(owner=user.profile)
    return render(request, 'fitapp/userLogs.html', {'logs': user_logs, 'user': user})

@login_required(login_url='/')
def update(request, user_id):
    user = User.objects.get(pk=user_id)
    user.profile.current = user.profile.current + 10
    while user.profile.current >= 100:
        print(user.profile.current)
        user.profile.current = user.profile.current - 100
        user.profile.level = user.profile.level + 1
    user.save()
    return render(request, 'fitapp/progress.html')

@login_required(login_url='/')
def log(request, logs_id):
    user = request.user
    template = loader.get_template('fitapp/log.html')
    log_accessed = get_object_or_404(Logs, pk=logs_id)
    log_comments = Comment.objects.filter(post=log_accessed)
    context = {'log' : log_accessed, 'comments': log_comments, 'user' : user}
    return HttpResponse(template.render(context, request))

# begin Creating Comments code #
@login_required(login_url='/')
def post_detail(request, logs_id):
    user = request.user
    template_name = loader.get_template('fitapp/log.html')
    post = get_object_or_404(Logs, pk=logs_id)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    context = {'log' : post, 'comments': comments, 'user' : user}

    return HttpResponse(template_name.render(context, request))
# end Creating Comments code #

@login_required(login_url='/')
def Achievements(request):
    try:
        user = request.user
        num = int((user.profile.level / 10)) + 10
    except User.DoesNotExist:
        raise Http404("User does not exist")
    return render(request, 'fitapp/achievements.html', {'user': user, 'num': num})

@login_required(login_url='/')
def deleteLog(request, logs_id):
    user = request.user.profile
    log = get_object_or_404(Logs, pk=logs_id)
    if log.owner != user:
        return HttpResponseRedirect('/')
    allComments = Comment.objects.all().filter(post=log)
    for comment in allComments:
        comment.delete()
    Logs.objects.filter(pk=logs_id).delete()
    return HttpResponseRedirect(reverse('fitapp:viewLogs'))

@login_required(login_url='/')
def leaderboard(request):
    try: 
        curruser = request.user
        currusername = request.user.username
        print(currusername)
        users = Profile.objects.all().order_by('-level','-current')
    except Profile.DoesNotExist:
        raise Http404("Profile does not exist")
    return render(request, 'fitapp/leaderboard.html', {'users': users, 'currusername': currusername})

def shareable(request, logs_id):
    template = loader.get_template('fitapp/shareable.html')
    log_accessed = get_object_or_404(Logs, pk=logs_id)
    log_comments = Comment.objects.filter(post=log_accessed)
    context = {'log' : log_accessed, 'comments': log_comments}    
    return HttpResponse(template.render(context, request))

fitapp/templates/fitapp/Logs.html
<!--
REFERENCES
*  Title: JavaScript to output html range slider values for multiple sliders
*  Author: Philipp, Kenny
*  Date: Jun 12 '19
*  URL:   https://stackoverflow.com/questions/56562129/javascript-to-output-html-range-slider-values-for-multiple-sliders
-->

{% extends 'fitapp/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block content%}
<h1 style="text-align: center"> Submit Log </h1>
<h5 style="text-align: center">Record your exercises here! The longer and more intense your workout is, the more XP you'll earn!</h5>
<br>


<form action="{% url 'fitapp:updatelogs' user.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
<!-- JavaScript to output html range slider values for multiple sliders code -->
    <div>
        <p>Minutes/Repetitions: <span id="demo"></span></p>
      </div>
      <script>
      var slider = document.getElementById("myRange");
      var output = document.getElementById("demo");
      output.innerHTML = slider.value;
      slider.oninput = function() {
        output.innerHTML = this.value;
      }
      </script>
<!-- JavaScript to output html range slider values for multiple sliders code -->
    <input type="submit" value="Submit">
</form>

<br><br><br>

{% endblock %}

fitapp/templates/fitapp/achievements.html
{% extends 'fitapp/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
{% block content%}
<h1 style="text-align: center"> Achievements </h1>
<h5 style="text-align: center">Get ideas for your next workout and learn how to do them safely! Press the "Achievement Done" button to earn the specified amount of XP!</h5>
<br>

<ul class="list-group">
    <li class="list-group-item">
        <h3 style="text-align: center" >Push-ups!</h3>
        <p style="text-align: center" >You can earn 10 XP for completing this achievement!</p>
        <p style="text-align: center"> After you finish {{ num }} push-ups, click the button below to earn this achievement!</p>
        <div style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1800" height="806" src="https://www.youtube.com/embed/4hCISQd_2Zk" title="YouTube video player"
                    frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

    <li style="text-align: center" class="list-group-item">
        <h3>Chest flies!</h3>
        <p>You can earn 10 XP for completing this achievement!</p>
        <p> After you finish {{ num }} chest flies, click the button below to earn this achievement!</p>
        <div style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1800" height="806" src="https://www.youtube.com/embed/cIRGs6uFHak" title="YouTube video player"
                    frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

    <li style="text-align: center" class="list-group-item">
        <h3>Dumbell Rows!</h3>
        <p>You can earn 10 XP for completing this achievement!</p>
        <p> After you finish {{ num }} dumbell rows on each side, click the button below to earn this achievement!</p>
        <div style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1904" height="806" src="https://www.youtube.com/embed/FXmzkvMH7SE" title="YouTube video player"
                    frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

    <li style="text-align: center" class="list-group-item">
        <h3>Bicep Curls!</h3>
        <p>You can earn 10 XP for completing this achievement!</p>
        <p> After you finish {{ num }} bicep curls, click the button below to earn this achievement!</p>
        <div style="text-align: center" style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1904" height="806" src="https://www.youtube.com/embed/41zei-ocKGw" title="YouTube video player" 
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

    <li style="text-align: center" class="list-group-item">
        <h3>Planks!</h3>
        <p>You can earn 10 XP for completing this achievement!</p>
        <p>After you finish {{ num }} minutes of planks, click the button below to earn this achievement!</p>
        <div style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1904" height="806" src="https://www.youtube.com/embed/fLHiWMbf1OM" title="YouTube video player" 
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

    <li style="text-align: center" class="list-group-item">
        <h3>Situps!</h3>
        <p>You can earn 10 XP for completing this achievement!</p>
        <p>After you finish {{ num }} situps, click the button below to earn this achievement!</p>
        <div style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1904" height="806" src="https://www.youtube.com/embed/FGqvlb20G90" title="YouTube video player" 
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

    <li style="text-align: center" class="list-group-item">
        <h3>Lunges!</h3>
        <p>You can earn 10 XP for completing this achievement!</p>
        <p>After you finish {{ num }} lunges, click the button below to earn this achievement!</p>
        <div style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1904" height="806" src="https://www.youtube.com/embed/OHtT-smKnfA" title="YouTube video player" 
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

    <li style="text-align: center" class="list-group-item">
        <h3>Squats!</h3>
        <p>You can earn 10 XP for completing this achievement!</p>
        <p>After you finish {{ num }} squats, click the button below to earn this achievement!</p>
        <div style="text-align: center" class="embed-responsive embed-responsive-16by9" style="width: 720px; height: 405px; margin: auto;">
            <iframe width="1904" height="806" src="https://www.youtube.com/embed/2dgneEJ0yjs" title="YouTube video player" 
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen></iframe>
        </div>
        <br>
        <form action="{% url 'fitapp:update' user.id %}" style="text-align: center" method="update" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Achievement Done!</button>
        </form>
    </li>

</ul>

<br>
<br>

{% endblock %}

fitapp/templates/fitapp/base.html
<!--
REFERENCES
*  Title: A Complete Beginner's Guide to Django - Part 4
*  Author: Vitor Frietas
*  Date: Sept 25, 2017
*  URL: https://simpleisbetterthancomplex.com/series/2017/09/25/a-complete-beginners-guide-to-django-part-4.html

-->

<html lang="en">
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Fitter Late Than Never</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/fitapp/progress/">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/fitapp/Logs/">Submit Log</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/fitapp/viewLogs/">View Logs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/fitapp/achievements/">Achievements</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/fitapp/leaderboard/">Leaderboard</a>
      </li>
      <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>-->
    </ul>
  </div>
</nav>

<!--basic stylings-->

<head>
  {% block head %}
  {% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Fitter Late than Never</title>
</head>

<body>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'fitapp/style.css' %}">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <!--<h1 class="mt-2">Django Tutorials!</h1>-->
        <hr class="mt-0 mb-4">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>


<!--footer-->
<footer class="bg-footer">
  {% block footer %}
  {% endblock %}
  <div class="card fixed-bottom">
    <div class="card-header text-center">
      <small> Fitter Late Than Never &copy; 2021 &nbsp; &nbsp; All Rights Reserved</small>
    </div>
  </div>
  <!-- <div class ="container text=center">
      <div class="footer fixed-bottom">CS 3240 Project</div>
    </div> -->
</footer>

</html>

fitapp/templates/fitapp/log.html
<!--    REFERENCES
*  Title: Creating Comments System With Django
*  Author: Django Central
*  URL: https://djangocentral.com/creating-comments-system-with-django/
*
*  Title: Share Button - Social Plugins
*  Author: Facebook
*  URL: https://developers.facebook.com/docs/plugins/share-button/
*
* -->
{% extends 'fitapp/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block head %}
<meta property="og:url" content="https://project-b-08.herokuapp.com/" />
<meta property="og:title" content="Fitter Late Than Never" />
<meta property="og:description" content="Share your recent workout today!" />
<meta property="og:image" content="https://images.emojiterra.com/twitter/512px/1f4aa.png" />
{% endblock %}

{% block content %}
<tl class="h1">{{log.owner.user.first_name}}'s {{log.date}} {{log.area}} Workout</tl>
<br>
<br>
<tr>Exercise: {{log.exercise}}</tr>
<br>
<tr>Date: {{log.date}}</tr>
<br>
<tr>Duration: {{log.duration}} minutes/repetitions</tr>
<br>
<tr>Intensity: {{log.intensity}}</tr>
<br>
<tr>Area: {{log.area}}</tr>
<br>
<tr>Owner: {{log.owner.user.first_name}}</tr>

{% if log.owner.user == user %}
    <form  action="{% url 'fitapp:deleteLog' log.id%}">
        <br><button type="submit" class="btn-danger">Delete this log (cannot be undone)</button>
    </form>

<!-- Facebook Share Button code -->
<div id="fb-root"></div>
<script>(function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-share-button" data-href="/fitapp/viewLogs/{{log.id}}/shareable" data-layout="button_count">
</div>
{% endif %}
<!-- end Facebook Share Button code -->

<!-- Comments System code -->
<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <div class="card-body">
                <h2>{{ comments.count }} comments</h2>
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span>
                    </p>
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8 card mb-4  mt-3 ">
            <div class="card-body">
                <h3>Leave a comment</h3>
                <form action="{% url 'fitapp:post_detail' log.id%}" method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text-area" placeholder="Title" name="name">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" rows="5"  type="text-area" placeholder="Comment" name="body"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!--end  Comments System code -->

<br>
<br>
{% endblock %}

fitapp/templates/fitapp/userLogs.html
{% extends 'fitapp/base.html' %}

{% block content%}
<h1 style="text-align: center"> {{user.first_name}}'s Logs </h1>

<br>

{%for whatever in logs%}
<tr>
    <td>
        <div style="text-align: center;">
        <a href="/fitapp/viewLogs/{{whatever.id}}" class="btn btn-primary">{{whatever.owner.user.first_name}}'s {{whatever.date}} {{whatever.area}} Workout</a>
    </div>
    </td><br>
        <hr>
</tr>

<br>

{%endfor%}
{% endblock %}